# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'games/libkmahjongg': '@same'
    'games/libkdegames': '@same'
    'frameworks/kconfig': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdeclarative': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/kxmlgui': '@stable'

Options:
    require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
